//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36392
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSASQueryAnalyzer.Client.Common.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 90, 255")]
        public global::System.Drawing.Color ColdCacheColor {
            get {
                return ((global::System.Drawing.Color)(this["ColdCacheColor"]));
            }
            set {
                this["ColdCacheColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200, 0, 0")]
        public global::System.Drawing.Color WarmCacheColor {
            get {
                return ((global::System.Drawing.Color)(this["WarmCacheColor"]));
            }
            set {
                this["WarmCacheColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color PartitionsColor {
            get {
                return ((global::System.Drawing.Color)(this["PartitionsColor"]));
            }
            set {
                this["PartitionsColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color AggregationsColor {
            get {
                return ((global::System.Drawing.Color)(this["AggregationsColor"]));
            }
            set {
                this["AggregationsColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color HighlightColor {
            get {
                return ((global::System.Drawing.Color)(this["HighlightColor"]));
            }
            set {
                this["HighlightColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ProfilerEventsColor {
            get {
                return ((global::System.Drawing.Color)(this["ProfilerEventsColor"]));
            }
            set {
                this["ProfilerEventsColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color CachesColor {
            get {
                return ((global::System.Drawing.Color)(this["CachesColor"]));
            }
            set {
                this["CachesColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color PerformanceCountersColor {
            get {
                return ((global::System.Drawing.Color)(this["PerformanceCountersColor"]));
            }
            set {
                this["PerformanceCountersColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("167, 198, 255")]
        public global::System.Drawing.Color ColdCacheGraphBarColor1 {
            get {
                return ((global::System.Drawing.Color)(this["ColdCacheGraphBarColor1"]));
            }
            set {
                this["ColdCacheGraphBarColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Window")]
        public global::System.Drawing.Color ColdCacheGraphBarColor2 {
            get {
                return ((global::System.Drawing.Color)(this["ColdCacheGraphBarColor2"]));
            }
            set {
                this["ColdCacheGraphBarColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 192, 192")]
        public global::System.Drawing.Color WarmCacheGraphBarColor1 {
            get {
                return ((global::System.Drawing.Color)(this["WarmCacheGraphBarColor1"]));
            }
            set {
                this["WarmCacheGraphBarColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Window")]
        public global::System.Drawing.Color WarmCacheGraphBarColor2 {
            get {
                return ((global::System.Drawing.Color)(this["WarmCacheGraphBarColor2"]));
            }
            set {
                this["WarmCacheGraphBarColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color SerializationActivitiesColor {
            get {
                return ((global::System.Drawing.Color)(this["SerializationActivitiesColor"]));
            }
            set {
                this["SerializationActivitiesColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AddInAutomaticallyCheckNewVersion {
            get {
                return ((bool)(this["AddInAutomaticallyCheckNewVersion"]));
            }
            set {
                this["AddInAutomaticallyCheckNewVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int TimelineEventsNumberThreshold {
            get {
                return ((int)(this["TimelineEventsNumberThreshold"]));
            }
            set {
                this["TimelineEventsNumberThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MaxRowsReturned {
            get {
                return ((int)(this["MaxRowsReturned"]));
            }
            set {
                this["MaxRowsReturned"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DebugEnabled {
            get {
                return ((bool)(this["DebugEnabled"]));
            }
            set {
                this["DebugEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ExecutionProgressActivitiesEnabled {
            get {
                return ((bool)(this["ExecutionProgressActivitiesEnabled"]));
            }
            set {
                this["ExecutionProgressActivitiesEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color RegularMeasuresColor {
            get {
                return ((global::System.Drawing.Color)(this["RegularMeasuresColor"]));
            }
            set {
                this["RegularMeasuresColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color NonEmptyActivitiesColor {
            get {
                return ((global::System.Drawing.Color)(this["NonEmptyActivitiesColor"]));
            }
            set {
                this["NonEmptyActivitiesColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color CachedDimensionsColor {
            get {
                return ((global::System.Drawing.Color)(this["CachedDimensionsColor"]));
            }
            set {
                this["CachedDimensionsColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color CalculatedMeasuresColor {
            get {
                return ((global::System.Drawing.Color)(this["CalculatedMeasuresColor"]));
            }
            set {
                this["CalculatedMeasuresColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color NonCachedDimensionsColor {
            get {
                return ((global::System.Drawing.Color)(this["NonCachedDimensionsColor"]));
            }
            set {
                this["NonCachedDimensionsColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TimelineCachesVisible {
            get {
                return ((bool)(this["TimelineCachesVisible"]));
            }
            set {
                this["TimelineCachesVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TimelineAggregationsVisible {
            get {
                return ((bool)(this["TimelineAggregationsVisible"]));
            }
            set {
                this["TimelineAggregationsVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TimelinePartitionsVisible {
            get {
                return ((bool)(this["TimelinePartitionsVisible"]));
            }
            set {
                this["TimelinePartitionsVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TimelineDimensionsVisible {
            get {
                return ((bool)(this["TimelineDimensionsVisible"]));
            }
            set {
                this["TimelineDimensionsVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TimelineMeasuresVisible {
            get {
                return ((bool)(this["TimelineMeasuresVisible"]));
            }
            set {
                this["TimelineMeasuresVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TimelineNonEmptyActivitiesVisible {
            get {
                return ((bool)(this["TimelineNonEmptyActivitiesVisible"]));
            }
            set {
                this["TimelineNonEmptyActivitiesVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TimelineSerializationActivitiesVisible {
            get {
                return ((bool)(this["TimelineSerializationActivitiesVisible"]));
            }
            set {
                this["TimelineSerializationActivitiesVisible"] = value;
            }
        }
    }
}
