// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SSASQueryAnalyzer.Client.SSMS.VSPackage
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidAsqaPackageString = "28672cc0-c8a7-4203-b4ce-d9c3e6216812";
        public const string guidSSMSMdxFileEditorContextString = "33f13ac3-80bb-4ecb-85bc-225435603a5e";
        public const string guidAsqaPackageCmdSetString = "fef8b856-4329-4a0e-a03b-364c1d1bff24";
        public const string guidImagesString = "9077ced1-9ddd-4f0a-bf33-185a69352188";
        public static Guid guidAsqaPackage = new Guid(guidAsqaPackageString);
        public static Guid guidSSMSMdxFileEditorContext = new Guid(guidSSMSMdxFileEditorContextString);
        public static Guid guidAsqaPackageCmdSet = new Guid(guidAsqaPackageCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int cmdidSSMSMdxFileEditorContext = 0x0051;
        public const int cmdidAsqaToolbar = 0x0010;
        public const int cmdidAsqaToolbarGroup = 0x0050;
        public const int cmdidAsqaToolbarCommandShowHelper = 0x0100;
        public const int cmdidAsqaToolbarCommandNewQuery = 0x0110;
        public const int cmdidAsqaToolbarCommandExecuteLiveAnalysis = 0x0120;
        public const int cmdidAsqaToolbarCommandExecuteBatchAnalysis = 0x0130;
        public const int cmdidAsqaToolbarCommandCreatePowershellScript = 0x0140;
        public const int cmdidAsqaToolbarCommandCreatePdfReport = 0x0150;
        public const int cmdidAsqaToolbarCommandFormatMDX = 0x0160;
        public const int cmdidAsqaContextMenu = 0x0500;
        public const int cmdidAsqaContextMenuCommandShowHelper = 0x1000;
        public const int cmdidAsqaContextMenuCommandExecuteLiveAnalysis = 0x1020;
        public const int cmdidAsqaContextMenuCommandExecuteBatchAnalysis = 0x1030;
        public const int cmdidAsqaContextMenuCommandCreatePowershellScript = 0x1040;
        public const int cmdidAsqaContextMenuCommandCreatePdfReport = 0x1050;
        public const int cmdidAsqaContextMenuCommandFormatMDX = 0x1060;
        public const int bmpAsqaShowHelper = 0x0001;
        public const int bmpAsqaNewQuery = 0x0002;
        public const int bmpAsqaExecuteLiveAnalysis = 0x0003;
        public const int bmpAsqaExecuteBatchAnalysis = 0x0004;
        public const int bmpAsqaCreatePowershellScript = 0x0005;
        public const int bmpAsqaCreatePdfReport = 0x0006;
        public const int bmpAsqaFormatMDX = 0x0007;
    }
}
